### PR TITLE
Migrate to Go modules for Go 1.22 compatibility

### LINKED ISSUE #127: switch from dep to Go modules
[dep has been archived since 2020 and deprecated in favor of Go modules](https://github.com/golang/dep). Would be great to see this project transition to Go modules in case it is still maintained.

### LINKED ISSUE #128: Is this still maintained? Last commit 3 years ago, not compatible with Go 1.22
Given that 
* the last commit was done a bit more than 3 years ago on Jan 6<sup>th</sup> 2021
* it would need to #127 for compatibility with upcoming Go 1.22

i am wondering if this project is still maintained, or should it be deprecated?

### PR DESCRIPTION
**Pull request by stefanb**
Provides compatibility with Go 1.22. From [Go 1.22 release notes](https://tip.golang.org/doc/go1.22#go-command):
> go get is no longer supported outside of a module in the legacy GOPATH mode (that is, with GO111MODULE=off). Other build commands, such as go build and go test, will continue to work indefinitely for legacy GOPATH programs.

Related:
* fixes #127
* fixes #128

### CODE REVIEW

**Comment by stefanb** [comment]
Done in https://github.com/github-release/github-release/commit/1d199d1c023bb971815f13ce5f06f5940b70cd2f

**Comment by chenrui333** [comment]
missed https://github.com/github-release/github-release/commit/1d199d1c023bb971815f13ce5f06f5940b70cd2f in 0.10.1 release

relates to https://github.com/Homebrew/homebrew-core/pull/175629

**Comment by stefanb** [comment]
It should be included in the next release.

**Comment by stefanb** [comment]
Perhaps they wanted to make a release before doing such a "drastic" change 😄

**Comment by stefanb** [comment]
Interestingly, there is no more v0.10.1 release:
https://github.com/github-release/github-release/releases

**Pull request closed without merging**
